import { CommandDef } from '../types';

/** Hand-authored halcmd command reference (signatures + short docs). */
export const HAL_COMMANDS: Record<string, CommandDef> = {
  loadrt: { name: 'loadrt', signature: 'loadrt module [name=value]... [count=N | names=a,b,...]', doc: 'Load a realtime HAL component (module) into the realtime environment.' },
  unloadrt: { name: 'unloadrt', signature: 'unloadrt module | all', doc: 'Unload a realtime component.' },
  loadusr: { name: 'loadusr', signature: 'loadusr [-W|-Wn name|-w|-i] program [args]...', doc: 'Start a user-space HAL component or program. -W waits until it is ready.' },
  unloadusr: { name: 'unloadusr', signature: 'unloadusr name | all', doc: 'Unload a user-space component.' },
  unload: { name: 'unload', signature: 'unload name | all', doc: 'Unload a realtime or user-space component.' },
  waitusr: { name: 'waitusr', signature: 'waitusr name', doc: 'Wait for a user-space component to exit.' },
  net: { name: 'net', signature: 'net signal-name pin-name [<=|=>] [pin-name]...', doc: 'Create a signal (if needed) and connect pins to it. The preferred way to wire HAL.' },
  newsig: { name: 'newsig', signature: 'newsig signal-name type', doc: 'Create a new signal of the given type (bit, float, s32, u32, ...). Usually unnecessary; net auto-creates signals.' },
  delsig: { name: 'delsig', signature: 'delsig signal-name | all', doc: 'Delete a signal.' },
  setp: { name: 'setp', signature: 'setp pin-or-param value', doc: 'Set the value of a pin or parameter that is not connected to a signal.' },
  sets: { name: 'sets', signature: 'sets signal-name value', doc: 'Set the value of a signal that has no writer pin.' },
  getp: { name: 'getp', signature: 'getp pin-or-param', doc: 'Print the value of a pin or parameter.' },
  gets: { name: 'gets', signature: 'gets signal-name', doc: 'Print the value of a signal.' },
  ptype: { name: 'ptype', signature: 'ptype pin-or-param', doc: 'Print the type of a pin or parameter.' },
  stype: { name: 'stype', signature: 'stype signal-name', doc: 'Print the type of a signal.' },
  linkps: { name: 'linkps', signature: 'linkps pin-name [=>] signal-name', doc: 'Link a pin to a signal (obsolete; use net).' },
  linksp: { name: 'linksp', signature: 'linksp signal-name [=>] pin-name', doc: 'Link a signal to a pin (obsolete; use net).' },
  linkpp: { name: 'linkpp', signature: 'linkpp pin1 pin2', doc: 'Link two pins via an anonymous signal (obsolete; use net).' },
  unlinkp: { name: 'unlinkp', signature: 'unlinkp pin-name', doc: 'Unlink a pin from whatever signal it is connected to.' },
  addf: { name: 'addf', signature: 'addf function thread [position]', doc: 'Add a function to a realtime thread, optionally at a given position.' },
  delf: { name: 'delf', signature: 'delf function thread', doc: 'Remove a function from a thread.' },
  initf: { name: 'initf', signature: 'initf function thread', doc: 'Run a function once at load time.' },
  start: { name: 'start', signature: 'start', doc: 'Start the realtime threads.' },
  stop: { name: 'stop', signature: 'stop', doc: 'Stop the realtime threads.' },
  show: { name: 'show', signature: 'show [type] [pattern]...', doc: 'Print HAL items (pin, sig, param, funct, thread, comp, ...).' },
  list: { name: 'list', signature: 'list type [pattern]...', doc: 'Print names of HAL items of the given type.' },
  save: { name: 'save', signature: 'save [type] [filename]', doc: 'Print or save the HAL configuration.' },
  source: { name: 'source', signature: 'source filename.hal', doc: 'Execute commands from another HAL file.' },
  alias: { name: 'alias', signature: 'alias pin|param original-name alias', doc: 'Create an alternate name for a pin or parameter.' },
  unalias: { name: 'unalias', signature: 'unalias pin|param alias', doc: 'Remove an alias.' },
  lock: { name: 'lock', signature: 'lock [all|tune|none]', doc: 'Lock HAL to prevent changes.' },
  unlock: { name: 'unlock', signature: 'unlock [all|tune]', doc: 'Unlock HAL to allow changes.' },
  status: { name: 'status', signature: 'status [lock|mem|all]', doc: 'Print status information about HAL.' },
  help: { name: 'help', signature: 'help [command]', doc: 'Print help for a command.' },
  echo: { name: 'echo', signature: 'echo', doc: 'Echo commands to stderr as they are executed.' },
  unecho: { name: 'unecho', signature: 'unecho', doc: 'Stop echoing commands.' },
  print: { name: 'print', signature: 'print [message]', doc: 'Print a message with source line info.' },
  debug: { name: 'debug', signature: 'debug [level]', doc: 'Get or set the rtapi message level.' },
  quit: { name: 'quit', signature: 'quit', doc: 'Exit an interactive halcmd session.' },
  exit: { name: 'exit', signature: 'exit', doc: 'Exit an interactive halcmd session.' },
};
